Some weights of the model checkpoint at google/bert_uncased_L-2_H-128_A-2 were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google/bert_uncased_L-2_H-128_A-2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:445: LightningDeprecationWarning: Setting `Trainer(gpus=0)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=0)` instead.
  rank_zero_deprecation(
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Reusing dataset glue (/Users/prabinnepal/.cache/huggingface/datasets/glue/cola/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 1083.33it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 12.88ba/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 15.36ba/s]
  | Name                   | Type                          | Params
-------------------------------------------------------------------------
0 | bert                   | BertForSequenceClassification | 4.4 M
1 | W                      | Linear                        | 258
2 | train_accuracy_metric  | Accuracy                      | 0
3 | val_accuracy_metric    | Accuracy                      | 0
4 | f1_metric              | F1Score                       | 0
5 | precision_macro_metric | Precision                     | 0
6 | recall_macro_metric    | Recall                        | 0
7 | precision_micro_metric | Precision                     | 0
8 | recall_micro_metric    | Recall                        | 0
-------------------------------------------------------------------------
4.4 M     Trainable params
0         Non-trainable params
4.4 M     Total params
17.546    Total estimated model params size (MB)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:219: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Sanity Checking DataLoader 0:   0%|                                                                             | 0/2 [00:00<?, ?it/s]----- tensor([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 0, 0, 1, 1])
Outputs-------- SequenceClassifierOutput(loss=tensor(0.6247), logits=tensor([[ 0.0706,  0.3655],
        [ 0.0818,  0.3211],
        [ 0.0595,  0.3412],
        [ 0.0037,  0.2870],
        [ 0.0546,  0.4200],
        [ 0.0468,  0.3048],
        [ 0.0304,  0.3148],
        [-0.0211,  0.3922],
        [ 0.0642,  0.2697],
        [ 0.0709,  0.3769],
        [ 0.0083,  0.3369],
        [ 0.0806,  0.3714],
        [ 0.0477,  0.3673],
        [-0.0103,  0.3001],
        [ 0.0445,  0.3376],
        [-0.0097,  0.3335],
        [-0.0489,  0.3469],
        [ 0.0535,  0.4150],
        [-0.0366,  0.2992],
        [-0.0216,  0.3629],
        [-0.0032,  0.3901],
        [ 0.0225,  0.4092],
        [ 0.0289,  0.2833],
        [ 0.0516,  0.2749],
        [-0.0115,  0.3165],
        [ 0.0193,  0.2932],
        [ 0.0138,  0.3741],
        [ 0.0085,  0.3714],
        [ 0.0915,  0.3460],
        [ 0.1104,  0.3536],
        [ 0.0879,  0.3236],
        [ 0.1127,  0.3270]]), hidden_states=None, attentions=None)
Traceback (most recent call last):
  File "/Users/prabinnepal/my_projects/MLOps/wandb_logging/train.py", line 36, in <module>
    main()
  File "/Users/prabinnepal/my_projects/MLOps/wandb_logging/train.py", line 32, in main
    trainer.fit(cola_model, cola_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 700, in fit
    self._call_and_handle_interrupt(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 654, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _run_train
    self._run_sanity_check()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1342, in _run_sanity_check
    val_loop.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1703, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/Users/prabinnepal/my_projects/MLOps/wandb_logging/model.py", line 66, in validation_step
    outputs = self.forward(
  File "/Users/prabinnepal/my_projects/MLOps/wandb_logging/model.py", line 42, in forward
    h_cls = outputs.last_hidden_state[:, 0]
AttributeError: 'SequenceClassifierOutput' object has no attribute 'last_hidden_state'